name: OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build k5
      working-directory: ./k5/os
      run: make build
    # - name: Build k3
    #   working-directory: ./k3/os
    #   run: make build
